---
pdf_document: default
author: "Esther Kho Yining"
date: "2024-03-12"
output:
  html_document: default
  pdf_document: default
title: "Week 8 Code-along and Challenge"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 8 Code-along
<br>

<br>

```{r, eval=TRUE,echo=TRUE}
# Tidy vs Non-Tidy (Slide 8) 
library(tidyverse)

tidydata <- tribble(
  ~country, ~year, ~cases, ~population,
  "Afghanistan", 1999, 745, 19987071,
  "Afghanistan", 2000, 2666, 20595360,
  "Brazil", 1999, 37737, 172006362,
  "Brazil", 2000, 80488, 174504898,
  "China", 1999, 212258, 1272915272,
  "China", 2000, 213766, 1280428583)

tidydata

nontidydata <- tribble(
  ~country,~year,~rate, 
  "Afghanistan", 1999, "745/19987071", 
  "Afghanistan", 2000, "2666/20595360", 
  "Brazil", 1999, "37737/172006362", 
  "Brazil", 2000, "80488/174504898", 
  "China", 1999, "212258/1272915272",
  "China", 2000, "213766/1280428583")

nontidydata
```

```{r, eval=TRUE,echo=TRUE}
# Why Tidy data? (Slide 9)
tidydata %>%
  group_by(year)%>%
  summarize(total_cases = sum(cases))
```

```{r, eval=TRUE,echo=TRUE}
# Tidy-ing data: Example-1 (Slide 11) 
nontidydata

tidieddata <- nontidydata %>% 
  separate(rate,into=c("cases","population"),
           sep="/")

tidieddata
```

```{r, eval=TRUE,echo=TRUE}
# Tidy-ing data: Example-1 (Slide 12) 
newtidieddata <- tidieddata %>%
 pivot_longer(
   cols = cases:population,
   names_to = "measurement",
   values_to = "value"
   )

newtidieddata
```

```{r, eval=TRUE,echo=TRUE}
# Tidy-ing data: Example-1 (Slide 13) 
ggplot(newtidieddata) +
  aes(x=year,y=value, colour=country) +
  geom_point() +
  geom_line(aes(group = country))+
  facet_wrap(~measurement) +
  theme_bw()
```

```{r, eval=TRUE,echo=TRUE}
# Tidy-ing data: Example-2 (Slide 14) 
df <- tribble(
  ~id, ~bp1, ~bp2,
  "A", 100, 120,
  "B", 140, 115,
  "C", 120, 125
  )

df

df %>%
 pivot_longer(
   cols = bp1:bp2,
   names_to = "measurement",
   values_to = "value"
   )
```

```{r, eval=TRUE,echo=TRUE}
# Reshaping data: Example-3 (Slide 18) 
newtidieddata

newtidieddata %>% 
 pivot_wider(names_from="measurement",
             values_from="value")
```

```{r, eval=TRUE,echo=TRUE}
# Reshaping data; Example-4 (Slide 19) 
df <- tribble(
  ~id, ~measurement, ~value,
  "A", "bp1", 100,
  "B", "bp1", 140,
  "B", "bp2", 115, 
  "A", "bp2", 120,
  "A", "bp3", 105
  )

df

df %>% 
 pivot_wider(
   names_from = measurement,
   values_from = value
   )
```

```{r, eval=TRUE,echo=TRUE}
# Calling an API (Slide 25)
chooseCRANmirror(ind=1)
install.packages(c("httr","jsonlite"))
library(httr)
library(jsonlite)
current_county_data_url <- "https://api.covidactnow.org/v2/counties.csv?apiKey=YOUR_KEY_HERE"
historic_county_data_url <- "https://api.covidactnow.org/v2/counties.timeseries.csv?apiKey=YOUR_KEY_HERE"
individual_loc_data_url <-
"https://api.covidactnow.org/v2/county/{state}.csv?apiKey=YOUR_KEY_HERE"
```
```{r, eval=TRUE,echo=TRUE}
# Calling an API (Slide 26)
current_county_data_url <-
"https://api.covidactnow.org/v2/counties.csv?apiKey=33382de96fd8441fb6c"
raw_data <- GET(current_county_data_url)
raw_data$status
raw_data$content
```

```{r, eval=TRUE,echo=TRUE}
# Calling an API (Slide 27)
historic_county_data_url <- "https://api.covidactnow.org/v2/counties.timeseries.csv?apiKey=33382de96fd8441fb6c1eca82b3bd4ec"
raw_data <- GET(historic_county_data_url)
raw_data$status
raw_data$content
```

```{r, eval=TRUE,echo=TRUE}
# Calling an API (Slide 28)
individual_loc_data_url <-
"https://api.covidactnow.org/v2/county/{49}.csv?apiKey=33382de96fd8441fb6c1eca82b3bd4ec"
raw_data <- GET(individual_loc_data_url)
raw_data$status
raw_data$content
```

# Week 8 Challenge

```{r, eval=TRUE,echo=TRUE}
# Part 1
library(tidyverse)
billboard
```

```{r, eval=TRUE,echo=TRUE}
# Part 1
billboardweek <- billboard %>% 
  pivot_longer(
    starts_with("wk"),
    names_to = "week",
    values_to = "rank",
    values_drop_na = TRUE
    ) %>% mutate(week=parse_number(week))

print(billboardweek)

ggplot(billboardweek, aes(x = week, y = rank)) +
  geom_line()
```

```{r, eval=TRUE,echo=TRUE}
# Part 2
cms_patient_experience
```

```{r, eval=TRUE,echo=TRUE}
# Part 2
cms_patient_experience_wider <- cms_patient_experience %>%
  pivot_wider(
    names_from = measure_cd, 
    values_from = prf_rate, 
    id_cols = starts_with("org")
    )

print(cms_patient_experience_wider)
```