---
pdf_document: default
author: "Esther Kho Yining"
date: "2024-03-05"
output:
  pdf_document: default
  html_document: default
title: "Challenge 7"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Challenge 7 
<br>

## I. ggplot2 
<br>

```{r, eval=TRUE,echo=TRUE}
# Load tidyverse and data (Slide 6)
library(tidyverse)
library(palmerpenguins)
glimpse(penguins)
```

### Palmer Penguins

```{r, eval=TRUE,echo=TRUE}
# a. start with the penguins data frame (Slide 8)
library(ggplot2)
ggplot(data = penguins)
```
<br>

```{r, eval=TRUE,echo=TRUE}
# b. map bill depth to the x-axis (Slide 9)
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm))
```
<br>
```{r, eval=TRUE,echo=TRUE}
# c. Map bill length to the y-axis (Slide 10)

ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm))
```
<br>

```{r, eval=TRUE,echo=TRUE}
# d. Represent each observation with a point (Slide 11)

ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm)) + 
 geom_point()
```
<br>

```{r, eval=TRUE,echo=TRUE}
# e. Map species to the colour of each point (Slide 12)
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point()
```
<br>

```{r, eval=TRUE,echo=TRUE}
# f. Title the plot "Bill depth and length (Slide 13)
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
 labs(title = "Bill depth and length")
```
<br>

```{r, eval=TRUE,echo=TRUE}
# g. Add the subtitle "Dimensions for Adelie, Chinstrap, and Gentoo Penguins" (Slide 14)
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
 labs(title = "Bill depth and length",
subtitle = "Dimensions for Adelie, 
Chinstrap, and Gentoo Penguins")
```
<br>

```{r, eval=TRUE,echo=TRUE}
# h. Label the x and y axes as "Bill depth (mm)" and "Bill length (mm)", respectively (Slide 15)
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
  labs(title = "Bill depth and length",
 subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
 x = "Bill depth (mm)", 
 y = "Bill length (mm)")
```
<br>

```{r, eval=TRUE,echo=TRUE}
# i. Label the legend "Species" (Slide 16)
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
 labs(title = "Bill depth and length",
 subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
 x = "Bill depth (mm)", y = "Bill length (mm)",
 colour = "Species")
```
<br>

```{r, eval=TRUE,echo=TRUE}
# j. Add a caption for the data source (Slide 17)

ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
  labs(title = "Bill depth and length",
 subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
 x = "Bill depth (mm)", y = "Bill length (mm)",
 colour = "Species",
 caption = "Source: Palmer Station LTER / palmerpenguins package")
```
<br>

```{r, eval=TRUE,echo=TRUE}
# k. Finally, use a discrete colour scale that is designed to be perceived by viewers with common forms of colour blindness. (Slide 18)
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
  labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)", y = "Bill length (mm)",
       colour = "Species",
       caption = "Source: Palmer Station LTER / palmerpenguins package")
scale_colour_viridis_d()
```
<br>

```{r, eval=TRUE,echo=TRUE}
# Palmer Penguins: Colour (Slide 22)
ggplot(penguins) + aes(x = bill_depth_mm, y = bill_length_mm,
 colour = species) +
 geom_point() + 
  scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
# Palmer Penguins: Shape 1 (Slide 23)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = island)) +
 geom_point() + scale_colour_viridis_d()
```
```{r, eval=TRUE,echo=TRUE}
# Palmer Penguins: Shape 2 (Slide 24)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species)) +
 geom_point() + scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
# Palmer Penguins: Size (Slide 25)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species, shape = species,
 size = body_mass_g)) +
 geom_point() + scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
# Alpha
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species, size = body_mass_g, alpha = flipper_length_mm)) +
 geom_point() + scale_colour_viridis_d()
```

### Mapping vs. Setting

```{r, eval=TRUE,echo=TRUE}
# Mapping
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm,
 size = body_mass_g,
 alpha = flipper_length_mm) +
 geom_point()
```
<br>

```{r, eval=TRUE,echo=TRUE}
# Setting
ggplot(penguins) + 
 aes(x = bill_depth_mm, 
 y = bill_length_mm) + 
 geom_point(size = 2, alpha = 0.5)
```

### Faceting

```{r, eval=TRUE,echo=TRUE}
# Faceting (Slide 29)
ggplot(penguins) +
 aes(x = bill_depth_mm, 
 y = bill_length_mm) + 
 geom_point() +
 facet_grid(species ~ island)
```

```{r, eval=TRUE,echo=TRUE}
# Facet 2 (Slide 30)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(species ~ sex)
```

```{r, eval=TRUE,echo=TRUE}
# Facet 3 (Slide 31)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(sex ~ species)
```

```{r, eval=TRUE,echo=TRUE}
# Facet 4 (Slide 32)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species)
```

```{r, eval=TRUE,echo=TRUE}
# Facet 5 (Slide 33)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species, ncol = 2)
```

```{r, eval=TRUE,echo=TRUE}
# Facet 6 (Slide 34)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(. ~ species)
```

```{r, eval=TRUE,echo=TRUE}
# Facet and colour (Slide 35)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d()

```

```{r, eval=TRUE,echo=TRUE}
# Facet and colour, no legend (Slide 36)
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d() +
 guides(color = "none")
```

<br>

## B. Visualising Numeric Variables

```{r, eval=TRUE,echo=TRUE}
# Load openintro and data (Slide 39)
library(openintro)
glimpse(loans_full_schema)
```

```{r, eval=TRUE,echo=TRUE}
# Selected variables (Slide 40)
loans <- loans_full_schema %>%
 select(loan_amount, interest_rate, term, grade, 
 state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```
<br>

### Histograms
```{r, eval=TRUE,echo=TRUE}
# Histogram (Slide 46)
ggplot(loans) + aes(x = loan_amount) +
 geom_histogram()
```

```{r, eval=TRUE,echo=TRUE}
# Histogram and binwidth=1000 (Slide 47)
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 1000)
```

```{r, eval=TRUE,echo=TRUE}
# Histogram and binwidth=5000 (Slide 48)
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 5000)
```

```{r, eval=TRUE,echo=TRUE}
# Histogram and binwidth=2000 (Slide 49)
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 20000)
```

```{r, eval=TRUE,echo=TRUE}
# Customising histograms (Slide 50)
ggplot(loans, aes(x = loan_amount)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)", y = "Frequency", title = "Amounts of Lending Club loans" )
```

### Categorical variable

```{r, eval=TRUE,echo=TRUE}
# Fill with a categorical variable (Slide 51) 
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
  geom_histogram(binwidth = 5000, alpha = 0.5) +
labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans")
```

```{r, eval=TRUE,echo=TRUE}
# Facet with a categorical variable (Slide 52)
ggplot(loans, aes(x = loan_amount, fill = homeownership)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
 facet_wrap(~ homeownership, nrow = 3)
```

```{r, eval=TRUE,echo=TRUE}
# Density plot (Slide 53)
ggplot(loans, aes(x = loan_amount)) +
 geom_density()
```

```{r, eval=TRUE,echo=TRUE}
# Density plots and adjusting bandwidth 1 (Slide 54)
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 0.5)
```

```{r, eval=TRUE,echo=TRUE}
# Density plots and adjusting bandwidth 2 (Slide 55)
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 1) 
```

```{r, eval=TRUE,echo=TRUE}
# Density plots and adjusting bandwidth 3 (Slide 56)
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2)
```

```{r, eval=TRUE,echo=TRUE}
# Customising density plots (Slide 57)
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2) +
 labs( x = "Loan amount ($)", y = "Density", title = "Amounts of Lending Club loans" )
```

```{r, eval=TRUE,echo=TRUE}
# Adding a categorical variable (Slide 58)
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_density(adjust = 2, alpha = 0.5) +
 labs(x = "Loan amount ($)",y = "Density",title = "Amounts of Lending Club loans", fill = "Homeownership")
```

### Box plot

```{r, eval=TRUE,echo=TRUE}
# Box plot (Slide 59)
ggplot(loans, aes(x = interest_rate)) +
 geom_boxplot()
```

```{r, eval=TRUE,echo=TRUE}
# Box plot and outliers (Slide 60)
ggplot(loans, aes(x = annual_income)) +
 geom_boxplot()
```

```{r, eval=TRUE,echo=TRUE}
# Customizing box plot (Slide 61)
ggplot(loans, aes(x = interest_rate)) +geom_boxplot() +labs(x = "Interest rate (%)",y = NULL,
 title = "Interest rates of Lending Club loans") +
 theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )
```

```{r, eval=TRUE,echo=TRUE}
# Adding a categoric variable (Slide 62)
ggplot(loans, aes(x = interest_rate,
y = grade)) +
  geom_boxplot() +
  labs(x = "Interest rate (%)",y = "Grade",title = "Interest rates of Lending Club loans",subtitle="by grade of loan")
```

### Scatterplot

```{r, eval=TRUE,echo=TRUE}
#  Scatterplot (Slide 63)
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) + geom_point()
```

### Hex plot

```{r, eval=TRUE,echo=TRUE}
# Hex plot 1 (Slide 64)
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
geom_hex()
```

```{r, eval=TRUE,echo=TRUE}
# Hex plot 2 (Slide 65) 
ggplot(loans %>% filter(debt_to_income < 100), aes(x = debt_to_income, y = interest_rate)) +
  geom_hex()
```

<br>

### III. Visualizing categoric variables

```{r, eval=TRUE,echo=TRUE}
# Bar plot (Slide 67) 
ggplot(loans, aes(x = homeownership)) +
 geom_bar()
```

```{r, eval=TRUE,echo=TRUE}
# Segmented bar plot 1 (Slide 68)
ggplot(loans, aes(x = homeownership, 
 fill = grade)) +
 geom_bar()
```

```{r, eval=TRUE,echo=TRUE}
# Segmented bar plot 2 (Slide 69)
ggplot(loans, aes(x = homeownership, fill = grade)) +
 geom_bar(position = "fill")
```

```{r, eval=TRUE,echo=TRUE}
# Customising bar plots (Slide 71)
ggplot(loans, aes(y = homeownership, fill = grade)) + geom_bar(position = "fill") +
labs( x = "Proportion", y = "Homeownership", fill = "Grade", title = "Grades of Lending Club loans", subtitle = "and homeownership of leeden")
```

### IV. Visualising variabes of varied types

```{r, eval=TRUE,echo=TRUE}
# Violin plots (Slide 73)
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
 geom_violin()
```

```{r, eval=TRUE,echo=TRUE}
# Ridge plots (Slide 74)
library(ggridges)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) + 
 geom_density_ridges(alpha = 0.5)
```
